/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptLuggageRequest' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'addConveyanceProfile' : IDL.Func([IDL.Null], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createLuggageRequest' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text], [], []),
  'createNetworkingPost' : IDL.Func([IDL.Null], [], []),
  'createSOS' : IDL.Func([IDL.Text], [], []),
  'findCoTravellers' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Vec(IDL.Text))],
      [],
      ['query'],
    ),
  'getActiveSOS' : IDL.Func([], [], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(IDL.Null)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConveyanceProfiles' : IDL.Func([IDL.Principal], [], ['query']),
  'getLuggageRequests' : IDL.Func([IDL.Text], [], ['query']),
  'getMessagesWithUser' : IDL.Func([IDL.Principal], [], ['query']),
  'getNetworkingPosts' : IDL.Func([IDL.Text], [], ['query']),
  'getTipsByCity' : IDL.Func([IDL.Text], [], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Null)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resolveSOS' : IDL.Func([IDL.Int], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Null], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptLuggageRequest' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'addConveyanceProfile' : IDL.Func([IDL.Null], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createLuggageRequest' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'createNetworkingPost' : IDL.Func([IDL.Null], [], []),
    'createSOS' : IDL.Func([IDL.Text], [], []),
    'findCoTravellers' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Vec(IDL.Text))],
        [],
        ['query'],
      ),
    'getActiveSOS' : IDL.Func([], [], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(IDL.Null)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConveyanceProfiles' : IDL.Func([IDL.Principal], [], ['query']),
    'getLuggageRequests' : IDL.Func([IDL.Text], [], ['query']),
    'getMessagesWithUser' : IDL.Func([IDL.Principal], [], ['query']),
    'getNetworkingPosts' : IDL.Func([IDL.Text], [], ['query']),
    'getTipsByCity' : IDL.Func([IDL.Text], [], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Null)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resolveSOS' : IDL.Func([IDL.Int], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Null], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };