/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptLuggageRequest' : ActorMethod<[string, bigint], undefined>,
  'addConveyanceProfile' : ActorMethod<[null], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createLuggageRequest' : ActorMethod<[string, number, string], undefined>,
  'createNetworkingPost' : ActorMethod<[null], undefined>,
  'createSOS' : ActorMethod<[string], undefined>,
  'findCoTravellers' : ActorMethod<
    [string, string, [] | [string], [] | [Array<string>]],
    undefined
  >,
  'getActiveSOS' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [null]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConveyanceProfiles' : ActorMethod<[Principal], undefined>,
  'getLuggageRequests' : ActorMethod<[string], undefined>,
  'getMessagesWithUser' : ActorMethod<[Principal], undefined>,
  'getNetworkingPosts' : ActorMethod<[string], undefined>,
  'getTipsByCity' : ActorMethod<[string], undefined>,
  'getUserProfile' : ActorMethod<[Principal], [] | [null]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resolveSOS' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[null], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];